### ISSUE TITLE
contact area of third carriage bolt not hexagonal

### ISSUE THREAD

**Issue by probably-Erwins-Cat** [JackJack3231/MiniSB-Extruder-Mounts#3]
![grafik](https://github.com/JackJack3231/MiniSB-Extruder-Mounts/assets/100243207/b2bfd1e6-f88e-4946-8143-2ed0fec57767)
 The contact area could be made hexagonal so it fits perfectly to the form of the x-carriage. Is there a reason why the hexagon was cut short here?

**Comment by JackJack3231** [comment]
The reason it's missing is because I used Mavericks LGX-Lite Mod as a base and he didn't include it on his and I never bothered/thought about adding it back.
I don't think it would affect the rigidity of the mount in any meaningful way, but also wouldn't hurt.

I'll probably add it with a future Update as it would allow me to move the hex nut back a few millimeters so a more standard M3x20 could be used instead of a M3x22. 
However I have to deal with some other projects first so it will take a few weeks.

**Comment by JackJack3231** [comment]
Added with d30720d95192b9bc3cdfc89e31ee7aa8b7fa5b88
